name: Python Syntax

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Specify the Python version you're using

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8
        run: flake8 ./ --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Flake8 with PEP 8 checks
        run: flake8 ./ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
